name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 9.0.3
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ">=0.18.1 <=1.0.0"
  flutter_country_selector:
    git:
      url: https://github.com/fuadmostafij6/flutter_country_selector.git
      ref: main
  circle_flags: ^4.0.0
  phone_numbers_parser:
    git:
      url: https://github.com/fuadmostafij6/phone_numbers_parser.git
      ref: dev
  diacritic: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
